#!/usr/bin/env python3
"""
Create hierarchical HTML tree visualization of attention weights.
Groups tokens by attention weight ranges and semantic structure.
"""
import argparse
import csv
import json
import re
from pathlib import Path
from typing import List, Dict, Any, Tuple
from collections import defaultdict


def parse_token_mapping(token_map_file: Path) -> List[str]:
    """
    Parse token mapping CSV file generated by translate_tokens.py.

    CSV format:
    row_index,token_id,token_text
    0,8948,system
    1,527,You
    2,35,>\n
    ...

    Token text is escaped (e.g., \\n instead of actual newline).
    This function un-escapes them.

    Returns list of token texts in row order.
    """
    print(f"Reading token mapping from: {token_map_file}")

    tokens = []

    with open(token_map_file, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader)  # Skip header

        for row in reader:
            if not row or len(row) < 3:
                continue

            # row_index, token_id, token_text (escaped)
            row_idx = int(row[0])
            escaped_text = row[2]

            # Un-escape the text by using codecs.decode with 'unicode_escape'
            # This converts \\n back to \n, \\t back to \t, etc.
            try:
                # For Python 3, we need to handle this carefully
                # The text is already a string with escaped sequences like '\\n'
                # We need to decode it properly
                import codecs
                token_text = codecs.decode(escaped_text, 'unicode_escape')
            except Exception:
                # If un-escaping fails, use as-is
                token_text = escaped_text

            tokens.append(token_text)

    print(f"Loaded {len(tokens)} tokens from mapping file")
    return tokens


def read_attention_weights(csv_file: Path) -> Tuple[List[int], List[List[float]]]:
    """Read attention weights from CSV."""
    print(f"Reading attention weights from: {csv_file}")

    token_ids = []
    attention_matrix = []

    with open(csv_file, 'r') as f:
        reader = csv.reader(f)
        next(reader)  # Skip header

        for row in reader:
            if not row:
                continue
            token_id = int(row[0])
            weights = [float(w) for w in row[1:] if w]

            token_ids.append(token_id)
            attention_matrix.append(weights)

    print(f"Read attention weights for {len(token_ids)} tokens")
    return token_ids, attention_matrix


def build_hierarchical_tree(
    tokens: List[str],
    token_ids: List[int],
    attention_matrix: List[List[float]],
    focus_token_idx: int = -1,
    min_weight: float = 0.0001,
    show_all_tokens: bool = False
) -> Dict[str, Any]:
    """
    Build hierarchical tree structure grouped by attention weight ranges.
    This creates a flame-graph-like structure.

    Args:
        show_all_tokens: If True, show all tokens regardless of min_weight threshold
    """
    if focus_token_idx < 0:
        focus_token_idx = len(token_ids) + focus_token_idx

    if focus_token_idx >= len(attention_matrix):
        raise ValueError(f"Focus token index {focus_token_idx} out of range")

    attention_weights = attention_matrix[focus_token_idx]

    def get_token_text(idx: int) -> str:
        if idx < len(tokens):
            text = tokens[idx]
            # Truncate very long tokens
            if len(text) > 50:
                text = text[:47] + "..."
            return text
        return f"<tok_{token_ids[idx] if idx < len(token_ids) else idx}>"

    # Define attention weight tiers for grouping
    tiers = [
        ("Very High (>0.1)", 0.1, float('inf')),
        ("High (0.01-0.1)", 0.01, 0.1),
        ("Medium (0.001-0.01)", 0.001, 0.01),
        ("Low (0.0001-0.001)", 0.0001, 0.001),
        ("Very Low (<0.0001)", 0, 0.0001),
    ]

    # Group tokens by tier
    tier_groups = defaultdict(list)

    for i, weight in enumerate(attention_weights):
        if i >= len(token_ids):
            continue

        # Skip low-weight tokens unless show_all_tokens is enabled
        if not show_all_tokens and weight < min_weight:
            continue

        token_text = get_token_text(i)

        # Find tier
        for tier_name, tier_min, tier_max in tiers:
            if tier_min <= weight < tier_max:
                tier_groups[tier_name].append({
                    "name": token_text,
                    "value": weight,
                    "token_idx": i,
                    "token_id": token_ids[i] if i < len(token_ids) else -1,
                })
                break

    # Build root node
    focus_text = get_token_text(focus_token_idx)
    root = {
        "name": f"Query: {focus_text}",
        "value": 1.0,
        "children": []
    }

    # Create tier nodes
    for tier_name, tier_min, tier_max in tiers:
        if tier_name not in tier_groups or not tier_groups[tier_name]:
            continue

        tokens_in_tier = tier_groups[tier_name]
        # Sort by attention weight descending
        tokens_in_tier.sort(key=lambda x: x["value"], reverse=True)

        total_weight = sum(t["value"] for t in tokens_in_tier)

        tier_node = {
            "name": f"{tier_name} ({len(tokens_in_tier)} tokens, Σ={total_weight:.4f})",
            "value": total_weight,
            "children": tokens_in_tier
        }

        root["children"].append(tier_node)

    return root


def generate_html_hierarchical(
    hierarchy: Dict[str, Any],
    output_file: Path,
    layer: int,
    head: int,
    focus_token_idx: int
):
    """Generate interactive HTML hierarchical tree visualization."""

    html_template = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attention Weights Hierarchical View - Layer {layer} Head {head}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f5f5f5;
        }}

        #header {{
            background: white;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}

        h1 {{
            margin: 0 0 10px 0;
            color: #333;
        }}

        .info {{
            color: #666;
            font-size: 14px;
            margin-top: 5px;
        }}

        #chart {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            overflow: auto;
        }}

        .node {{
            cursor: pointer;
        }}

        .node rect {{
            stroke: white;
            stroke-width: 2px;
        }}

        .node text {{
            font-size: 11px;
            pointer-events: none;
            fill: white;
        }}

        #tooltip {{
            position: absolute;
            background: rgba(0, 0, 0, 0.9);
            color: white;
            padding: 12px;
            border-radius: 6px;
            font-size: 13px;
            pointer-events: none;
            display: none;
            z-index: 1000;
            max-width: 300px;
        }}

        #controls {{
            background: white;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}

        button {{
            padding: 8px 16px;
            margin-right: 10px;
            background: #2196F3;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
        }}

        button:hover {{
            background: #1976D2;
        }}

        .legend {{
            margin-top: 20px;
            padding: 15px;
            background: #f9f9f9;
            border-radius: 4px;
        }}

        .legend-item {{
            display: inline-block;
            margin-right: 20px;
            margin-bottom: 8px;
        }}

        .legend-color {{
            display: inline-block;
            width: 20px;
            height: 20px;
            margin-right: 5px;
            vertical-align: middle;
            border: 1px solid #ccc;
        }}
    </style>
</head>
<body>
    <div id="header">
        <h1>Attention Weights Hierarchical Tree</h1>
        <div class="info">
            <strong>Layer:</strong> {layer} |
            <strong>Head:</strong> {head} |
            <strong>Focus Token Index:</strong> {focus_token_idx}
        </div>
        <div class="info">
            Tokens are grouped by attention weight ranges. Hover for details, click to zoom.
        </div>

        <div class="legend">
            <strong>Color Scale:</strong><br>
            <div class="legend-item">
                <span class="legend-color" style="background-color: #d73027;"></span>
                Very High (>0.1)
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background-color: #fc8d59;"></span>
                High (0.01-0.1)
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background-color: #fee08b;"></span>
                Medium (0.001-0.01)
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background-color: #91cf60;"></span>
                Low (0.0001-0.001)
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background-color: #1a9850;"></span>
                Very Low (<0.0001)
            </div>
        </div>
    </div>

    <div id="controls">
        <button onclick="resetView()">Reset View</button>
        <button onclick="expandAll()">Expand All</button>
        <button onclick="collapseAll()">Collapse All</button>
    </div>

    <div id="chart"></div>
    <div id="tooltip"></div>

    <script src="https://d3js.org/d3.v7.min.js"></script>
    <script>
        const data = {data_json};

        const width = Math.max(1400, window.innerWidth - 100);
        const height = 800;

        const partition = d3.partition()
            .size([width, height])
            .padding(1);

        const svg = d3.select("#chart")
            .append("svg")
            .attr("width", width)
            .attr("height", height);

        const tooltip = d3.select("#tooltip");

        // Color scale based on tier/weight
        function getColor(d) {{
            if (d.depth === 0) return "#1976D2";  // root
            if (d.depth === 1) {{
                // Tier level
                const name = d.data.name;
                if (name.includes("Very High")) return "#d73027";
                if (name.includes("High")) return "#fc8d59";
                if (name.includes("Medium")) return "#fee08b";
                if (name.includes("Low (0.0001")) return "#91cf60";
                if (name.includes("Very Low")) return "#1a9850";
            }}
            // Leaf tokens - color by weight
            const weight = d.data.value;
            if (weight >= 0.1) return "#d73027";
            if (weight >= 0.01) return "#fc8d59";
            if (weight >= 0.001) return "#fee08b";
            if (weight >= 0.0001) return "#91cf60";
            return "#1a9850";
        }}

        function render(data) {{
            svg.selectAll("*").remove();

            const root = d3.hierarchy(data)
                .sum(d => d.value || 0)
                .sort((a, b) => b.value - a.value);

            partition(root);

            const nodes = svg.selectAll("g")
                .data(root.descendants())
                .enter()
                .append("g")
                .attr("class", "node")
                .attr("transform", d => `translate(${{d.x0}},${{d.y0}})`);

            nodes.append("rect")
                .attr("width", d => d.x1 - d.x0)
                .attr("height", d => d.y1 - d.y0)
                .attr("fill", d => getColor(d))
                .attr("opacity", 0.85)
                .on("mouseover", function(event, d) {{
                    d3.select(this).attr("opacity", 1);

                    let html = `<strong>${{d.data.name}}</strong><br>`;

                    if (d.data.token_idx !== undefined) {{
                        html += `Token Index: ${{d.data.token_idx}}<br>`;
                        html += `Token ID: ${{d.data.token_id}}<br>`;
                    }}

                    if (d.data.value !== undefined) {{
                        html += `Value: ${{d.data.value.toFixed(6)}}<br>`;
                    }}

                    html += `Depth: ${{d.depth}}`;

                    tooltip
                        .style("display", "block")
                        .style("left", (event.pageX + 10) + "px")
                        .style("top", (event.pageY - 10) + "px")
                        .html(html);
                }})
                .on("mouseout", function() {{
                    d3.select(this).attr("opacity", 0.85);
                    tooltip.style("display", "none");
                }})
                .on("click", function(event, d) {{
                    event.stopPropagation();
                    zoom(d);
                }});

            nodes.append("text")
                .attr("x", 4)
                .attr("y", 14)
                .text(d => {{
                    const width = d.x1 - d.x0;
                    if (width < 60) return "";
                    let name = d.data.name;
                    const maxChars = Math.floor(width / 7);
                    if (name.length > maxChars) {{
                        name = name.substring(0, maxChars - 3) + "...";
                    }}
                    return name;
                }})
                .attr("fill", "white")
                .style("text-shadow", "1px 1px 2px rgba(0,0,0,0.8)");
        }}

        let currentRoot = data;

        function zoom(d) {{
            currentRoot = d.data;
            render(d.data);
        }}

        function resetView() {{
            currentRoot = data;
            render(data);
        }}

        function expandAll() {{
            // Already expanded by default in partition layout
            render(currentRoot);
        }}

        function collapseAll() {{
            resetView();
        }}

        // Initial render
        render(data);
    </script>
</body>
</html>"""

    data_json = json.dumps(hierarchy, indent=2)

    html_content = html_template.format(
        layer=layer,
        head=head,
        focus_token_idx=focus_token_idx,
        data_json=data_json
    )

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html_content)

    print(f"Generated HTML visualization: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate hierarchical tree visualization of attention weights',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage - output: {csv_name}_focus8641_viz.html (last token by default)
  python visualize_attention_hierarchical.py \\
      --csv attn_weights_request_000001_layer_00_head_00.csv \\
      --tokens attn_weights_request_000001_layer_00_head_00_tokens.csv \\
      --layer 0 --head 0

  # Show ALL tokens - output: {csv_name}_focus8641_all_tokens_viz.html
  python visualize_attention_hierarchical.py \\
      --csv attn_weights.csv \\
      --tokens attn_weights_tokens.csv \\
      --show-all

  # Specific token - output: {csv_name}_focus1000_viz.html
  python visualize_attention_hierarchical.py \\
      --csv attn_weights.csv \\
      --tokens attn_weights_tokens.csv \\
      --focus-token 1000

  # Custom output location (override auto-generation)
  python visualize_attention_hierarchical.py \\
      --csv attn_weights.csv \\
      --tokens attn_weights_tokens.csv \\
      --output /custom/path/my_viz.html
        """
    )

    parser.add_argument('--csv', required=True, help='Path to CSV file with attention weights')
    parser.add_argument('--tokens', required=True, help='Path to token mapping CSV file (generated by translate_tokens.py)')
    parser.add_argument('--output', default=None, help='Output HTML file (default: auto-generate in same dir as CSV)')
    parser.add_argument('--focus-token', type=int, default=-1, help='Token index to focus on (-1 for last)')
    parser.add_argument('--min-weight', type=float, default=0.0001, help='Minimum attention weight to include')
    parser.add_argument('--show-all', action='store_true', help='Show all tokens regardless of min-weight threshold')
    parser.add_argument('--layer', type=int, default=0, help='Layer number (for display)')
    parser.add_argument('--head', type=int, default=0, help='Head number (for display)')

    args = parser.parse_args()

    csv_file = Path(args.csv)
    token_map_file = Path(args.tokens)

    if not csv_file.exists():
        print(f"Error: CSV file not found: {csv_file}")
        return 1

    if not token_map_file.exists():
        print(f"Error: Token mapping file not found: {token_map_file}")
        return 1

    tokens = parse_token_mapping(token_map_file)
    token_ids, attention_matrix = read_attention_weights(csv_file)

    # Calculate actual focus token index (resolve negative indices)
    focus_token_idx = args.focus_token
    if focus_token_idx < 0:
        focus_token_idx = len(token_ids) + focus_token_idx

    # Auto-generate output filename if not specified
    if args.output is None:
        # Get CSV file stem (e.g., "attn_weights_request_000001_layer_00_head_00")
        csv_stem = csv_file.stem

        # Add focus token index to filename
        focus_suffix = f"_focus{focus_token_idx}"

        # Add mode suffix
        if args.show_all:
            mode_suffix = "_all_tokens"
        else:
            mode_suffix = ""

        # Combine: {csv_stem}_focus{idx}[_all_tokens]_viz.html
        output_file = csv_file.parent / f"{csv_stem}{focus_suffix}{mode_suffix}_viz.html"
    else:
        output_file = Path(args.output)

    print(f"Building hierarchical tree for token index {args.focus_token}...")
    if args.show_all:
        print("  Note: --show-all enabled, displaying ALL tokens regardless of weight")
    hierarchy = build_hierarchical_tree(
        tokens,
        token_ids,
        attention_matrix,
        args.focus_token,
        args.min_weight,
        args.show_all
    )

    generate_html_hierarchical(
        hierarchy,
        output_file,
        args.layer,
        args.head,
        args.focus_token if args.focus_token >= 0 else len(token_ids) + args.focus_token
    )

    print(f"\nDone! Open {output_file} in your browser to view the visualization.")
    print(f"Total tiers: {len(hierarchy.get('children', []))}")

    return 0


if __name__ == '__main__':
    exit(main())
